## Практическое задание

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.


In [1]:
import numpy as np

A = np.zeros((4,2))
B = np.zeros((4,2))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
C=np.dot(A, B)
print(f'Матрица AB\n{C}')
print(f'Матрица AB\n{np.shape(C)}')
C=np.dot(B, A)
print(f'Матрица BА\n{C}')
print(f'Матрица BА\n{np.shape(C)}')

Матрица A
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Матрица B
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

а) Перемножить нельзя

In [2]:
import numpy as np

A = np.zeros((2,5))
B = np.zeros((5,3))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
C=np.dot(A, B)
print(f'Матрица AB\n{C}')
print(f'Матрица AB\n{np.shape(C)}')
C=np.dot(B, A)
print(f'Матрица BА\n{C}')
print(f'Матрица BА\n{np.shape(C)}')

Матрица A
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Матрица B
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Матрица AB
[[0. 0. 0.]
 [0. 0. 0.]]
Матрица AB
(2, 3)


ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

б) AB 2X3 BA перемножить нельзя

In [3]:
import numpy as np

A = np.zeros((8,3))
B = np.zeros((3,8))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
C=np.dot(A, B)
print(f'Матрица AB\n{C}')
print(f'Матрица AB\n{np.shape(C)}')
C=np.dot(B, A)
print(f'Матрица BА\n{C}')
print(f'Матрица BА\n{np.shape(C)}')

Матрица A
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Матрица B
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Матрица AB
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Матрица AB
(8, 8)
Матрица BА
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Матрица BА
(3, 3)


с) AB 8x8, BA 3x3

In [4]:
import numpy as np

A = np.zeros((4,4))
B = np.zeros((4,4))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
C=np.dot(A, B)
print(f'Матрица AB\n{C}')
print(f'Матрица AB\n{np.shape(C)}')
C=np.dot(B, A)
print(f'Матрица BА\n{C}')
print(f'Матрица BА\n{np.shape(C)}')

Матрица A
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Матрица B
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Матрица AB
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Матрица AB
(4, 4)
Матрица BА
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Матрица BА
(4, 4)


d) AB и BA 4X4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


In [5]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица С = A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BА\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BА
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица 3𝐴−2𝐵+4𝐶\n{3 * A - 2 * B + 4 * C}')

Матрица 3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [7]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'Матрица 𝐴*𝐴𝑇\n{np.dot(A, A.T)}')
print(f'Матрица 𝐴𝑇*𝐴\n{np.dot(A.T, A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица 𝐴*𝐴𝑇
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица 𝐴𝑇*𝐴
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.