## Практическое задание

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

  

###  a) $$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}; = sin(x)\cdot sin(x) - cos(x)\cdot (-cos(x)) = sin^{2}(x) + cos^{2}(x) = 1$$ 




    
### б) $$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4\cdot 5\cdot 9=180 $$
    
 

In [3]:
import numpy as np
a = np.array([[4,2,3],[0,5,1],[0,0,9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')


Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180



### в) $$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=7\cdot (12−15)−8\cdot (6−12)+9\cdot (5−8)=−21+48−27=0$$  

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')


Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0



__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})= 4^{2}=16$;
    
   б) $det(A^{T})=det(A) = 4$;
    
   в) $det(2A)=2^{n}det(A)=4\cdot2^{n}$.
   


__3.__  Доказать, что матрица

### $$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.


In [4]:
import numpy as np
a = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')


Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


Матрица вырожденная, т.к. ее определитель равен 0.

__4.__ Найти ранг матрицы:

   а) 
   ### $$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}$$



In [5]:
import numpy as np

a = np.array([[1,2,3],[1,1,1],[2,3,4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


### $$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & -1 & -2
\end{pmatrix}$$


In [6]:
import numpy as np

a = np.array([[1,2,3],[0,-1,-2],[0,-1,-2]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


 б) 
   ### $$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$



In [7]:
import numpy as np

a = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


### $$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$

In [8]:
import numpy as np

a = np.array([[0,0,2,1],[0,0,0,1],[0,0,0,0],[2,3,5,6]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
